'use client';

import { FormEvent, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import type { User } from '@supabase/supabase-js';
import { supabaseBrowser } from '@/lib/supabase-browser';

type Props = { open: boolean; onClose: () => void; onAuthenticated: (user: User, message: string) => void };
const ease = [0.16, 1, 0.3, 1] as const;

export default function AuthModal({ open, onClose, onAuthenticated }: Props) {
  const [mode, setMode] = useState<'sign-in' | 'sign-up'>('sign-in'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSubmitting(true); setMessage(''); const result = mode === 'sign-in' ? await supabaseBrowser.auth.signInWithPassword({ email, password }) : await supabaseBrowser.auth.signUp({ email, password }); if (result.error) setMessage(result.error.message); else if (result.data.user) { onAuthenticated(result.data.user, mode === 'sign-up' && !result.data.session ? 'Check your email to confirm your account.' : 'Authentication successful.'); if (result.data.session) onClose(); } setIsSubmitting(false); };
  const field = 'h-11 w-full rounded border border-[#E4E4E7] bg-white px-3.5 py-2.5 text-sm text-[#09090B] outline-none placeholder:text-[#A1A1AA] focus:border-[#09090B] focus:outline-none focus:ring-2 focus:ring-[#09090B] focus:ring-offset-2';
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 flex items-end justify-center bg-[#09090B]/20 p-4 backdrop-blur-sm sm:items-center" role="dialog" aria-modal="true" aria-labelledby="auth-title" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2, ease }}><motion.div className="w-full max-w-md rounded border border-[#E4E4E7] bg-white p-5 shadow-none sm:p-7" initial={{ opacity: 0, scale: 0.98, y: 4 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.98, y: 4 }} transition={{ duration: 0.2, ease }}><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-wider text-[#71717A]">Private workspace</p><h2 id="auth-title" className="mt-2 text-xl font-medium tracking-tight text-[#09090B]">{mode === 'sign-in' ? 'Welcome back' : 'Create your account'}</h2><p className="mt-2 text-sm leading-relaxed text-[#52525B]">Keep experiment memory tied to your team identity.</p></div><button type="button" onClick={onClose} className="rounded px-2 py-1 text-sm text-[#71717A] hover:bg-[#F4F4F5] focus:outline-none focus:ring-2 focus:ring-[#09090B] focus:ring-offset-2">Close</button></div><form onSubmit={submit} className="mt-7 space-y-4"><div><label htmlFor="auth-email" className="mb-2 block text-sm font-medium text-[#09090B]">Email</label><input id="auth-email" type="email" required autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} className={field} /></div><div><label htmlFor="auth-password" className="mb-2 block text-sm font-medium text-[#09090B]">Password</label><input id="auth-password" type="password" required minLength={6} autoComplete={mode === 'sign-in' ? 'current-password' : 'new-password'} value={password} onChange={event => setPassword(event.target.value)} className={field} /></div>{message && <p className="rounded border border-[#E4E4E7] bg-[#F4F4F5] px-3 py-3 text-sm leading-relaxed text-[#52525B]" role="alert">{message}</p>}<button type="submit" disabled={isSubmitting} className="flex h-11 w-full items-center justify-center rounded bg-[#09090B] text-sm font-medium text-white hover:bg-[#27272A] focus:outline-none focus:ring-2 focus:ring-[#09090B] focus:ring-offset-2 disabled:opacity-60">{isSubmitting ? 'Working...' : mode === 'sign-in' ? 'Sign in' : 'Create account'}</button></form><button type="button" onClick={() => { setMode(mode === 'sign-in' ? 'sign-up' : 'sign-in'); setMessage(''); }} className="mt-5 w-full rounded py-2 text-center text-sm text-[#52525B] underline-offset-4 hover:text-[#09090B] hover:underline focus:outline-none focus:ring-2 focus:ring-[#09090B] focus:ring-offset-2">{mode === 'sign-in' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></motion.div></motion.div>}</AnimatePresence>;
}
